
export const CategoryAction = {
    SINGLE_CATEGORY: 'SINGLE_CATEGORY',
    GET_CATEGORY_LIST: 'GET_CATEGORY_LIST'
}

export const WatchLaterAction = {
    ADD_TO_WATCHLATER: 'ADD_TO_WATCHLATER',
    REMOVE_FROM_WATCHLATER: 'REMOVE_FROM_WATCHLATER'
}

export const playlistmanagment = {
    CREATE_GLOBAL_PLAYLISTS: 'CREATE_GLOBAL_PLAYLISTS',
    REMOVE_PLAYLIST_FROM_GLOBAL: "REMOVE_PLAYLIST_FROM_GLOBAL",
    SET_CURRENT_VIDEO: 'SET_CURRENT_VIDEO',
    UNSET_CURRENT_VIDEO: 'UNSET_CURRENT_VIDEO'
}

export const likeAction = {
    ADD_TO_LIKES: 'ADD_TO_LIKES',
    REMOVE_FROM_LIKES: 'REMOVE_FROM_LIKES'
}